<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('transaksis')->insert([
            [
                // "id" => 1,
                "tanggal_transaksi" => '2020-12-21 00:00:00',
                "tanggal_ambil" => '2020-12-21 00:00:00',
                "metode_pembayaran" => 'Transfer',
                "status_pesanan" => 'Belum Bayar',
                // "status_pembayaran" => 'lunas',
                // "status_pengiriman" => 'sudah dikirim',
                "jenis_pengiriman" => 'Kurir',
                "potongan_poin" => 50,
                "poin_pesanan" => 250,
                "harga_setelah_poin" => 25000,
                "harga_total" => 120000,
                "id_customer" => 1,
            ],
            [
                // "id" => 2,
                "tanggal_transaksi" => '2020-12-22 00:00:00',
                "tanggal_ambil" => '2020-12-23 00:00:00',
                "metode_pembayaran" => 'Bank Transfer',
                "status_pesanan" => 'Belum Bayar',
                "jenis_pengiriman" => 'Ojol',
                "potongan_poin" => 30,
                "poin_pesanan" => 150,
                "harga_setelah_poin" => 15000,
                "harga_total" => 80000,
                "id_customer" => 2,
            ],
            [
                // "id" => 3,
                "tanggal_transaksi" => '2020-12-23 00:00:00',
                "tanggal_ambil" => '2020-12-24 00:00:00',
                "metode_pembayaran" => 'Cash',
                "status_pesanan" => 'Sudah Dibayar',
                "jenis_pengiriman" => 'Pickup',
                "potongan_poin" => 100,
                "poin_pesanan" => 300,
                "harga_setelah_poin" => 30000,
                "harga_total" => 150000,
                "id_customer" => 3,
            ],
            [
                // "id" => 4,
                "tanggal_transaksi" => '2020-12-24 00:00:00',
                "tanggal_ambil" => '2020-12-25 00:00:00',
                "metode_pembayaran" => 'Credit Card',
                "status_pesanan" => 'Sudah Dipick-Up',
                "jenis_pengiriman" => 'Ojol',
                "potongan_poin" => 20,
                "poin_pesanan" => 100,
                "harga_setelah_poin" => 10000,
                "harga_total" => 70000,
                "id_customer" => 1,
            ],
            [
                // "id" => 5,
                "tanggal_transaksi" => '2020-12-25 00:00:00',
                "tanggal_ambil" => '2020-12-26 00:00:00',
                "metode_pembayaran" => 'Bank Transfer',
                "status_pesanan" => 'Sedang Dikirim',
                "jenis_pengiriman" => 'Kurir',
                "potongan_poin" => 70,
                "poin_pesanan" => 350,
                "harga_setelah_poin" => 35000,
                "harga_total" => 200000,
                "id_customer" => 1,
            ],
            [
                // "id" => 6,
                "tanggal_transaksi" => '2024-5-26 00:00:00',
                "tanggal_ambil" => '2024-5-27 00:00:00',
                "metode_pembayaran" => 'Cash',
                "status_pesanan" => 'Sudah Dibayar',
                "jenis_pengiriman" => 'Pickup',
                "potongan_poin" => 80,
                "poin_pesanan" => 400,
                "harga_setelah_poin" => 40000,
                "harga_total" => 250000,
                "id_customer" => 3,
            ],
            [
                // "id" => 7,
                "tanggal_transaksi" => '2024-5-27 00:00:00',
                "tanggal_ambil" => '2024-5-28 00:00:00',
                "metode_pembayaran" => 'Credit Card',
                "status_pesanan" => 'Siap Dipick-Up',
                "jenis_pengiriman" => 'Ojol',
                "potongan_poin" => 40,
                "poin_pesanan" => 200,
                "harga_setelah_poin" => 20000,
                "harga_total" => 100000,
                "id_customer" => 1,
            ],
            [
                // "id" => 8,
                "tanggal_transaksi" => '2024-5-28 00:00:00',
                "tanggal_ambil" => '2024-5-29 00:00:00',
                "metode_pembayaran" => 'Bank Transfer',
                "status_pesanan" => 'Sudah Dibayar',
                "jenis_pengiriman" => 'Kurir',
                "potongan_poin" => 90,
                "poin_pesanan" => 450,
                "harga_setelah_poin" => 45000,
                "harga_total" => 300000,
                "id_customer" => 2,
            ],
            [
                // "id" => 9,
                "tanggal_transaksi" => '2024-5-29 00:00:00',
                "tanggal_ambil" => '2024-5-30 00:00:00',
                "metode_pembayaran" => 'Cash',
                "status_pesanan" => 'Sudah Dibayar',
                "jenis_pengiriman" => 'Pickup',
                "potongan_poin" => 60,
                "poin_pesanan" => 300,
                "harga_setelah_poin" => 30000,
                "harga_total" => 180000,
                "id_customer" => 3,
            ],
            [
                // "id" => 10,
                "tanggal_transaksi" => '2024-5-30 00:00:00',
                "tanggal_ambil" => '2024-5-31 00:00:00',
                "metode_pembayaran" => 'Credit Card',
                "status_pesanan" => 'Sudah Dipick-Up',
                "jenis_pengiriman" => 'Ojol',
                "potongan_poin" => 10,
                "poin_pesanan" => 50,
                "harga_setelah_poin" => 5000,
                "harga_total" => 50000,
                "id_customer" => 1,
            ],
            // untuk bulan 6 dan status pesanan Selesai
            [
                // "id" => 11,
                "tanggal_transaksi" => '2024-6-1 00:00:00',
                "tanggal_ambil" => '2024-6-2 00:00:00',
                "metode_pembayaran" => 'Bank Transfer',
                "status_pesanan" => 'Selesai',
                "jenis_pengiriman" => 'Kurir',
                "potongan_poin" => 90,
                "poin_pesanan" => 450,
                "harga_setelah_poin" => 45000,
                "harga_total" => 300000,
                "id_customer" => 2,
            ],
            [
                // "id" => 12,
                "tanggal_transaksi" => '2024-6-2 00:00:00',
                "tanggal_ambil" => '2024-6-3 00:00:00',
                "metode_pembayaran" => 'Cash',
                "status_pesanan" => 'Selesai',
                "jenis_pengiriman" => 'Pickup',
                "potongan_poin" => 60,
                "poin_pesanan" => 300,
                "harga_setelah_poin" => 30000,
                "harga_total" => 180000,
                "id_customer" => 3,
            ],
            [
                // "id" => 13,
                "tanggal_transaksi" => '2024-6-3 00:00:00',
                "tanggal_ambil" => '2024-6-4 00:00:00',
                "metode_pembayaran" => 'Credit Card',
                "status_pesanan" => 'Selesai',
                "jenis_pengiriman" => 'Ojol',
                "potongan_poin" => 10,
                "poin_pesanan" => 50,
                "harga_setelah_poin" => 5000,
                "harga_total" => 50000,
                "id_customer" => 1,
            ],
            [
                // "id" => 14,
                "tanggal_transaksi" => '2024-6-4 00:00:00',
                "tanggal_ambil" => '2024-6-5 00:00:00',
                "metode_pembayaran" => 'Bank Transfer',
                "status_pesanan" => 'Selesai',
                "jenis_pengiriman" => 'Kurir',
                "potongan_poin" => 90,
                "poin_pesanan" => 450,
                "harga_setelah_poin" => 45000,
                "harga_total" => 300000,
                "id_customer" => 2,
            ],
            // [
            //     "tanggal_transaksi" => '2024-6-5 00:00:00',
            //     "tanggal_ambil" => '2024-6-6 00:00:00',
            //     "metode_pembayaran" => 'Bank Transfer',
            //     "status_pesanan" => 'Belum Bayar',
            //     "jenis_pengiriman" => 'Kurir',
            //     "potongan_poin" => 10,
            //     "poin_pesanan" => 200,
            //     "harga_setelah_poin" => 20000,
            //     "harga_total" => 200000,
            //     "id_customer" => 2,
            // ],
            // [
            //     "tanggal_transaksi" => '2024-6-6 00:00:00',
            //     "tanggal_ambil" => '2024-6-7 00:500:00',
            //     "metode_pembayaran" => 'Cash',
            //     "status_pesanan" => 'Siap Dipick-Up',
            //     "jenis_pengiriman" => 'Kurir',
            //     "potongan_poin" => 20,
            //     "poin_pesanan" => 250,
            //     "harga_setelah_poin" => 25000,
            //     "harga_total" => 250000,
            //     "id_customer" => 1,
            // ]
        ]);
    }
}
